ALTER TABLE social_details DROP FOREIGN KEY fk_social_details_id_medrec;
ALTER TABLE social_details DROP FOREIGN KEY fk_social_details_id_doc;
ALTER TABLE patient_medical_record DROP FOREIGN KEY fk_patient_medical_record_id_socdet;
ALTER TABLE patient_medical_record DROP FOREIGN KEY fk_patient_medical_record_id_blgrp;
ALTER TABLE patient_medical_record DROP FOREIGN KEY fk_patient_medical_record_id_doc;
ALTER TABLE patient_medical_record DROP FOREIGN KEY fk_patient_medical_record_id_gpsc;
ALTER TABLE patient_medical_record DROP FOREIGN KEY fk_patient_medical_record_id_addr;
ALTER TABLE doctor DROP FOREIGN KEY fk_doctor_id_socdet;
ALTER TABLE doctor DROP FOREIGN KEY fk_doctor_id_gpsc;
ALTER TABLE gps_coordinates DROP FOREIGN KEY fk_gps_coordinates_id_medrec;
ALTER TABLE gps_coordinates DROP FOREIGN KEY fk_gps_coordinates_id_doc;
ALTER TABLE appointement DROP FOREIGN KEY fk_appointement_id_diag;
ALTER TABLE appointement DROP FOREIGN KEY fk_appointement_id_gpsc;
ALTER TABLE appointement DROP FOREIGN KEY fk_appointement_id_medrec;
ALTER TABLE appointement DROP FOREIGN KEY fk_appointement_id_doc;
ALTER TABLE appointement DROP FOREIGN KEY fk_appointement_id_addr;
ALTER TABLE medical_site DROP FOREIGN KEY fk_medical_site_id_addr;
ALTER TABLE doctor_diagnostic DROP FOREIGN KEY fk_doctor_diagnostic_id_medrec;
ALTER TABLE doctor_diagnostic DROP FOREIGN KEY fk_doctor_diagnostic_id_doc;
ALTER TABLE imagery DROP FOREIGN KEY fk_imagery_id_diag;
ALTER TABLE numerical DROP FOREIGN KEY fk_Decimalal_id_diag;
ALTER TABLE practice DROP FOREIGN KEY fk_practice_id_doc;
ALTER TABLE practice DROP FOREIGN KEY fk_practice_id_prtyp;
ALTER TABLE belong DROP FOREIGN KEY fk_belong_id_medsite;
ALTER TABLE belong DROP FOREIGN KEY fk_belong_id_doc;
ALTER TABLE have_relatives_with DROP FOREIGN KEY fk_have_relatives_with_id_medrec_child;
ALTER TABLE have_relatives_with DROP FOREIGN KEY fk_have_relatives_with_id_medrec_father;
ALTER TABLE is_allergy DROP FOREIGN KEY fk_is_allergy_id_allergy;
ALTER TABLE is_allergy DROP FOREIGN KEY fk_is_allergy_id_medrec;
ALTER TABLE is_genetic DROP FOREIGN KEY fk_is_genetic_id_gen;
ALTER TABLE is_genetic DROP FOREIGN KEY fk_is_genetic_id_medrec;
ALTER TABLE illness_probability DROP FOREIGN KEY fk_illness_probability_id_ill;
ALTER TABLE illness_probability DROP FOREIGN KEY fk_illness_probability_id_diag;
DROP TABLE IF EXISTS social_details;
DROP TABLE IF EXISTS blood_group;
DROP TABLE IF EXISTS patient_medical_record;
DROP TABLE IF EXISTS doctor;
DROP TABLE IF EXISTS profession_type;
DROP TABLE IF EXISTS gps_coordinates;
DROP TABLE IF EXISTS appointement;
DROP TABLE IF EXISTS address;
DROP TABLE IF EXISTS medical_site;
DROP TABLE IF EXISTS doctor_diagnostic;
DROP TABLE IF EXISTS imagery;
DROP TABLE IF EXISTS allergy;
DROP TABLE IF EXISTS genetic;
DROP TABLE IF EXISTS illness;
DROP TABLE IF EXISTS symptom;
DROP TABLE IF EXISTS numerical;
DROP TABLE IF EXISTS practice;
DROP TABLE IF EXISTS belong;
DROP TABLE IF EXISTS have_relatives_with;
DROP TABLE IF EXISTS is_allergy;
DROP TABLE IF EXISTS is_genetic;
DROP TABLE IF EXISTS illness_probability;