CREATE TABLE IF NOT EXISTS social_details ( id_socdet INT (11) UNSIGNED auto_increment NOT NULL, firstname VARCHAR (25), lastname VARCHAR (50), gender BOOLEAN, birthaddr VARCHAR (50), birthzipcode VARCHAR (5), birthdate DATE, phonenumber VARCHAR (10), picture VARCHAR (100), id_medrec INT UNSIGNED, id_doc INT UNSIGNED, PRIMARY KEY (id_socdet), UNIQUE (phonenumber) ) engine = innodb;
CREATE TABLE IF NOT EXISTS patient_medical_record ( id_medrec INT (11) UNSIGNED auto_increment NOT NULL, height TINYINT UNSIGNED, weight TINYINT UNSIGNED, socialsecuritynumber VARCHAR (13), id_socdet INT UNSIGNED, id_blgrp INT UNSIGNED, id_doc INT UNSIGNED, id_gpsc INT UNSIGNED, id_addr INT UNSIGNED, PRIMARY KEY (id_medrec), UNIQUE (socialsecuritynumber) ) engine = innodb;
CREATE TABLE IF NOT EXISTS allergy ( id_allergy INT(11) UNSIGNED auto_increment NOT NULL, name VARCHAR(25), PRIMARY KEY (id_allergy), UNIQUE (name) ) engine = innodb;
CREATE TABLE IF NOT EXISTS genetic ( id_gen INT(11) UNSIGNED auto_increment NOT NULL, name VARCHAR(25), PRIMARY KEY (id_gen), UNIQUE (name) ) engine = innodb;
CREATE TABLE IF NOT EXISTS blood_group ( id_blgrp INT (11) UNSIGNED auto_increment NOT NULL, groupname VARCHAR (3), PRIMARY KEY (id_blgrp), UNIQUE (groupname) ) engine = innodb;
CREATE TABLE IF NOT EXISTS doctor ( id_doc INT (11) UNSIGNED auto_increment NOT NULL, rpps VARCHAR (25), id_socdet INT UNSIGNED, id_gpsc INT UNSIGNED, PRIMARY KEY (id_doc), UNIQUE (rpps) ) engine = innodb;
CREATE TABLE IF NOT EXISTS profession_type ( id_prtyp INT (11) UNSIGNED auto_increment NOT NULL, name VARCHAR (50), PRIMARY KEY (id_prtyp), UNIQUE (name) ) engine = innodb;
CREATE TABLE IF NOT EXISTS gps_coordinates ( id_gpsc INT (11) UNSIGNED auto_increment NOT NULL, longitude VARCHAR (25), latitude VARCHAR (25), id_medrec INT UNSIGNED, id_doc INT UNSIGNED, PRIMARY KEY (id_gpsc) ) engine = innodb;
CREATE TABLE IF NOT EXISTS appointement ( id_appoi INT (11) UNSIGNED auto_increment NOT NULL, date_appoi DATE, hours_appoi TIME, id_diag INT UNSIGNED, id_gpsc INT UNSIGNED, id_medrec INT UNSIGNED, id_doc INT UNSIGNED, id_addr INT UNSIGNED, PRIMARY KEY (id_appoi) ) engine = innodb;
CREATE TABLE IF NOT EXISTS address ( id_addr INT (11) UNSIGNED auto_increment NOT NULL, number TINYINT UNSIGNED, street VARCHAR (50), zipcode SMALLINT UNSIGNED, PRIMARY KEY (id_addr) ) engine = innodb;
CREATE TABLE IF NOT EXISTS medical_site ( id_medsite INT (11) UNSIGNED auto_increment NOT NULL, name VARCHAR (25), id_addr INT UNSIGNED, PRIMARY KEY (id_medsite) ) engine = innodb;
CREATE TABLE IF NOT EXISTS doctor_diagnostic ( id_diag INT (11) UNSIGNED auto_increment NOT NULL, criticity FLOAT, date_diag DATE, id_medrec INT UNSIGNED, id_doc INT UNSIGNED, PRIMARY KEY (id_diag) ) engine = innodb;
CREATE TABLE IF NOT EXISTS imagery ( id_img INT (11) UNSIGNED auto_increment NOT NULL, name VARCHAR (50), image VARCHAR (100), id_diag INT UNSIGNED, PRIMARY KEY (id_img) ) engine = innodb;
CREATE TABLE IF NOT EXISTS illness ( id_ill INT(11) UNSIGNED auto_increment NOT NULL, name TEXT, PRIMARY KEY (id_ill) ) engine = innodb;
CREATE TABLE IF NOT EXISTS symptom ( id_symp INT(11) UNSIGNED auto_increment NOT NULL, name TEXT, spec_value FLOAT, PRIMARY KEY (id_symp) ) engine = innodb;
CREATE TABLE IF NOT EXISTS numerical ( id_num INT (11) UNSIGNED auto_increment NOT NULL, name VARCHAR (25), value INT, id_diag INT UNSIGNED, PRIMARY KEY (id_num) ) engine = innodb;
CREATE TABLE IF NOT EXISTS practice ( id_doc INT UNSIGNED NOT NULL, id_prtyp INT UNSIGNED NOT NULL, PRIMARY KEY (id_doc, id_prtyp) ) engine = innodb;
CREATE TABLE IF NOT EXISTS belong ( id_medsite INT UNSIGNED NOT NULL, id_doc INT UNSIGNED NOT NULL, PRIMARY KEY (id_medsite, id_doc) ) engine = innodb;CREATE TABLE IF NOT EXISTS have_relatives_with ( id_medrec_child INT UNSIGNED NOT NULL, id_medrec_father INT UNSIGNED NOT NULL, PRIMARY KEY (id_medrec_child, id_medrec_father) ) engine = innodb;
CREATE TABLE IF NOT EXISTS is_allergy ( id_medrec INT UNSIGNED NOT NULL, id_allergy INT UNSIGNED NOT NULL, PRIMARY KEY (id_medrec, id_allergy) ) engine = innodb;
CREATE TABLE IF NOT EXISTS is_genetic ( id_medrec INT UNSIGNED NOT NULL, id_gen INT UNSIGNED NOT NULL, PRIMARY KEY (id_medrec, id_gen) ) engine = innodb;
CREATE TABLE IF NOT EXISTS illness_probability ( id_diag INT UNSIGNED NOT NULL, id_ill INT UNSIGNED NOT NULL, probability FLOAT UNSIGNED, PRIMARY KEY(id_diag, id_ill) ) engine = innodb;
ALTER TABLE social_details ADD CONSTRAINT fk_social_details_id_medrec FOREIGN KEY (id_medrec) REFERENCES patient_medical_record(id_medrec);
ALTER TABLE social_details ADD CONSTRAINT fk_social_details_id_doc FOREIGN KEY (id_doc) REFERENCES doctor (id_doc);
ALTER TABLE patient_medical_record ADD CONSTRAINT fk_patient_medical_record_id_socdet FOREIGN KEY (id_socdet) REFERENCES social_details(id_socdet);
ALTER TABLE patient_medical_record ADD CONSTRAINT fk_patient_medical_record_id_blgrp FOREIGN KEY (id_blgrp) REFERENCES blood_group(id_blgrp);
ALTER TABLE patient_medical_record ADD CONSTRAINT fk_patient_medical_record_id_doc FOREIGN KEY (id_doc) REFERENCES doctor(id_doc);
ALTER TABLE patient_medical_record ADD CONSTRAINT fk_patient_medical_record_id_gpsc FOREIGN KEY (id_gpsc) REFERENCES gps_coordinates(id_gpsc);
ALTER TABLE patient_medical_record ADD CONSTRAINT fk_patient_medical_record_id_addr FOREIGN KEY (id_addr) REFERENCES address(id_addr);
ALTER TABLE doctor ADD CONSTRAINT fk_doctor_id_socdet FOREIGN KEY (id_socdet) REFERENCES social_details(id_socdet);
ALTER TABLE doctor ADD CONSTRAINT fk_doctor_id_gpsc FOREIGN KEY (id_gpsc) REFERENCES gps_coordinates(id_gpsc);
ALTER TABLE gps_coordinates ADD CONSTRAINT fk_gps_coordinates_id_medrec FOREIGN KEY (id_medrec) REFERENCES patient_medical_record(id_medrec);
ALTER TABLE gps_coordinates ADD CONSTRAINT fk_gps_coordinates_id_doc FOREIGN KEY (id_doc) REFERENCES doctor(id_doc);
ALTER TABLE appointement ADD CONSTRAINT fk_appointement_id_diag FOREIGN KEY (id_diag) REFERENCES doctor_diagnostic(id_diag);
ALTER TABLE appointement ADD CONSTRAINT fk_appointement_id_gpsc FOREIGN KEY (id_gpsc) REFERENCES gps_coordinates(id_gpsc);
ALTER TABLE appointement ADD CONSTRAINT fk_appointement_id_medrec FOREIGN KEY (id_medrec) REFERENCES patient_medical_record(id_medrec);
ALTER TABLE appointement ADD CONSTRAINT fk_appointement_id_doc FOREIGN KEY (id_doc) REFERENCES doctor(id_doc);
ALTER TABLE imagery ADD CONSTRAINT fk_imagery_id_diag FOREIGN KEY (id_diag) REFERENCES doctor_diagnostic(id_diag);
ALTER TABLE numerical ADD CONSTRAINT fk_decimalal_id_diag FOREIGN KEY (id_diag) REFERENCES doctor_diagnostic(id_diag);
ALTER TABLE practice ADD CONSTRAINT fk_practice_id_doc FOREIGN KEY (id_doc) REFERENCES doctor(id_doc);
ALTER TABLE practice ADD CONSTRAINT fk_practice_id_prtyp FOREIGN KEY (id_prtyp) REFERENCES profession_type(id_prtyp);
ALTER TABLE belong ADD CONSTRAINT fk_belong_id_medsite FOREIGN KEY (id_medsite) REFERENCES medical_site(id_medsite);
ALTER TABLE belong ADD CONSTRAINT fk_belong_id_doc FOREIGN KEY (id_doc) REFERENCES doctor(id_doc);
ALTER TABLE have_relatives_with ADD CONSTRAINT fk_have_relatives_with_id_medrec_child FOREIGN KEY (id_medrec_child) REFERENCES patient_medical_record(id_medrec);
ALTER TABLE have_relatives_with ADD CONSTRAINT fk_have_relatives_with_id_medrec_father FOREIGN KEY (id_medrec_father) REFERENCES patient_medical_record(id_medrec);
ALTER TABLE is_allergy ADD CONSTRAINT fk_is_allergy_id_medrec FOREIGN KEY (id_medrec) REFERENCES patient_medical_record(id_medrec);
ALTER TABLE is_allergy ADD CONSTRAINT fk_is_allergy_id_allergy FOREIGN KEY (id_allergy) REFERENCES allergy(id_allergy);
ALTER TABLE is_genetic ADD CONSTRAINT fk_is_genetic_id_medrec FOREIGN KEY (id_medrec) REFERENCES patient_medical_record(id_medrec);
ALTER TABLE is_genetic ADD CONSTRAINT fk_is_genetic_id_gen FOREIGN KEY (id_gen) REFERENCES genetic(id_gen);
ALTER TABLE illness_probability ADD CONSTRAINT fk_illness_probability_id_diag FOREIGN KEY(id_diag) REFERENCES doctor_diagnostic(id_diag);
ALTER TABLE illness_probability ADD CONSTRAINT fk_illness_probability_id_ill FOREIGN KEY(id_ill) REFERENCES illness(id_ill);
